# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/07_gas.reaction.ipynb.

# %% auto 0
__all__ = ['GasReaction']

# %% ../../nbs/07_gas.reaction.ipynb 4
# from exex.basics import *

# %% ../../nbs/07_gas.reaction.ipynb 5
class GasReaction: pass
