# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_reaction.core.ipynb.

# %% auto 0
__all__ = ['Reaction']

# %% ../../nbs/02_reaction.core.ipynb 3
import pandas as pd
from fastcore.test import test_eq
import chemlib
import pint

from ..compound.gas import Gas
from ..compound.core import *

# %% ../../nbs/02_reaction.core.ipynb 4
class Reaction:
    def __init__(
        self,
        reactants: list[Compound], # the list of reactants
        products: list[Compound] # the list of products
    ) -> None:
        #self.chem = chemlib.Reaction(reactants=reactants, products=products)
        self.reactants = reactants
        self.products = products
    
    def total_property(
        self,
        name: str # the name of the property
    ) -> list[float, float]: # the total property of reactants and products
        
        total_reactant = 0
        for reactant in self.reactants:
            if not name in reactant.properties: pass
            #total_reactant += reactant.properties[name]
            pass
        
        total_product = 0
    
        return total_reactant, total_product
