# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_core.event.ipynb.

# %% auto 0
__all__ = ['Event']

# %% ../../nbs/00_core.event.ipynb 5
class Event(list):
    def __call__(self, *args, **kwargs):
        for item in self:
            item(*args, **kwargs)
