# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_core.universe.ipynb.

# %% auto 0
__all__ = ['Universe']

# %% ../../nbs/00_core.universe.ipynb 4
from abc import ABC, abstractmethod

from ..imports import *
from .law import Law
from .system import System

# %% ../../nbs/00_core.universe.ipynb 5
@docs
class Universe(ABC):
    def __init__(self):
        self._laws: list[Law] = L([])

    _docs = dict(cls_doc="An abstract base class for create a new universe")
