# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_compound.core.ipynb.

# %% auto 0
__all__ = ['Matter', 'Compound']

# %% ../../nbs/01_compound.core.ipynb 3
from ..core import *

# %% ../../nbs/01_compound.core.ipynb 4
class Matter:
    pass

# %% ../../nbs/01_compound.core.ipynb 6
class Compound(Matter):
    def __init__(self):
        self._properties = dict()
        self._laws = []
    
    def add_laws(self, laws):
        for law in laws:
            self._laws.append(law(compound=self))
