# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_compound.gas.ipynb.

# %% auto 0
__all__ = ['MassMoleRatio', 'IdealGasLaw', 'Gas']

# %% ../../nbs/01_compound.gas.ipynb 3
from ..core import *
from .core import *

# %% ../../nbs/01_compound.gas.ipynb 6
class MassMoleRatio(Law):
    def __init__(self, compound):
        super().__init__()
        self.compound = compound
        self._properties = [Mass, Mole]
        self.init_properties()

# %% ../../nbs/01_compound.gas.ipynb 9
class IdealGasLaw(Law):
    def __init__(self, compound = Compound()):
        super().__init__()
        self.compound = compound
        # self._properties = {
        #     'pressure': Pressure(),
        #     'volume': Volume(),
        #     'mole': Mole(),
        #     'temperature': Temperature()
        # }
        self._properties = [Pressure, Volume, Mole, Temperature]
        self.init_properties()
        
    def add_properties_to_compound(self):
        pass
    
    def compute(self):
        #return self.compound._properties['pressure'] / self.compound._properties
        pass

# %% ../../nbs/01_compound.gas.ipynb 13
class Gas(Compound):
    def __init__(self):
        super().__init__()
        
        self.add_laws([MassMoleRatio, IdealGasLaw])
