# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_environment.core.ipynb.

# %% auto 0
__all__ = ['Environment', 'Container', 'OpenContainer', 'ClosedContainer']

# %% ../nbs/03_environment.core.ipynb 4
class Environment:
    def __init__(self):
        self.properties = dict()

# %% ../nbs/03_environment.core.ipynb 6
class Container(Environment):
    def __init__(self):
        self.properties = []

# %% ../nbs/03_environment.core.ipynb 7
class OpenContainer(Container):
    pass

# %% ../nbs/03_environment.core.ipynb 8
class ClosedContainer(Container):
    pass
