# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_our_universe.ipynb.

# %% auto 0
__all__ = ['OurUniverse', 'ConservationOfMass', 'ConservationOfEnergy', 'ConservationOfElectricCharge']

# %% ../nbs/05_our_universe.ipynb 4
from abc import ABC, abstractmethod

from .imports import *
from .core.all import *

# %% ../nbs/05_our_universe.ipynb 5
@docs
class OurUniverse(Universe):
    _docs = dict(
        cls_doc="The universe that has the law of physics from our universe (yeah you and me)"
    )

# %% ../nbs/05_our_universe.ipynb 9
@docs
class ConservationOfMass(Law):
    def __init__(self):
        pass

    def __bool__(self):
        pass

    _docs = dict(cls_doc="The sum of all masses in the universe")

# %% ../nbs/05_our_universe.ipynb 10
@docs
class ConservationOfEnergy:
    _docs = dict(cls_doc="The sum of all energies in the universe")

# %% ../nbs/05_our_universe.ipynb 11
@docs
class ConservationOfElectricCharge:
    _docs = dict(cls_doc="The sum of all electric charges in the universe")
