# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_symbolic.ipynb.

# %% auto 0
__all__ = ['Symbol', 'Function', 'Equation']

# %% ../nbs/00_symbolic.ipynb 4
from .imports import *

# %% ../nbs/00_symbolic.ipynb 6
@docs
class Symbol(sympy.core.symbol.Symbol):
    
    def __new__(cls, name):
        obj = sympy.core.symbol.Symbol.__new__(cls, name)
        return obj
    
    def set_data(self, data):
        self._data = data
    
    @property
    def data(self): return self._data
    
    _docs = dict(cls_doc='The symbol',
                 set_data='Set data',
                 data = 'Set data')

# %% ../nbs/00_symbolic.ipynb 18
class Function(sympy.core.function.Function):
    def __new__(cls, name):
        obj = sympy.core.function.Function.__new__(cls, name)
        return obj

# %% ../nbs/00_symbolic.ipynb 22
class Equation():
    pass
