# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_system.ipynb.

# %% auto 0
__all__ = ['System']

# %% ../nbs/00_system.ipynb 4
class System:
    def __init__(self):
        self._current_timestep = 0
        self.reactions = []
        self.universe = None
