# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/0_utils.ipynb.

# %% auto 0
__all__ = ['SUB', 'REV_SUB', 'camel_to_snake', 'snake_name', 'str2fml', 'fml2str']

# %% ../nbs/0_utils.ipynb 4
import re

from fastcore.test import test_eq

# %% ../nbs/0_utils.ipynb 6
def camel_to_snake(
    name: str # the string that you want to convert
    ) -> str: # converted string
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', name).lower()

# %% ../nbs/0_utils.ipynb 11
def snake_name(x) -> str: # return the snake name style
    "Get the snake style name of an instance"
    
    if type(x) == type: return camel_to_snake(x.__name__)
    return camel_to_snake(x.__class__.__name__)

# %% ../nbs/0_utils.ipynb 21
SUB = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")
REV_SUB = str.maketrans("₀₁₂₃₄₅₆₇₈₉", "0123456789")

# %% ../nbs/0_utils.ipynb 23
def str2fml(x: str) -> str:
    return x.translate(SUB)

# %% ../nbs/0_utils.ipynb 28
def fml2str(x: str) -> str:
    return x.translate(REV_SUB)
