# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_solver.ipynb.

# %% auto 0
__all__ = ['Solver']

# %% ../nbs/04_solver.ipynb 4
from sympy.solvers import solve

# %% ../nbs/04_solver.ipynb 5
class Solver:
    pass
